config/routes.rb
Rentalutions::Application.routes.draw do

  resources :launchsubscribers

  root :to => 'launchsubscribers#new', :as => :home

end

app/models/launchsubscriber.rb
class Launchsubscriber < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/launchsubscribers_controller.rb
class LaunchsubscribersController < ApplicationController
  # GET /launchsubscribers
  # GET /launchsubscribers.json
  def index
    @launchsubscribers = Launchsubscriber.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @launchsubscribers }
    end
  end

  # GET /launchsubscribers/1
  # GET /launchsubscribers/1.json
  def show
    @launchsubscriber = Launchsubscriber.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @launchsubscriber }
    end
  end

  # GET /launchsubscribers/new
  # GET /launchsubscribers/new.json
  def new
    @launchsubscriber = Launchsubscriber.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @launchsubscriber }
    end
  end

  # GET /launchsubscribers/1/edit
  def edit
    @launchsubscriber = Launchsubscriber.find(params[:id])
  end

  # POST /launchsubscribers
  # POST /launchsubscribers.json
  def create
    @launchsubscriber = Launchsubscriber.new(params[:launchsubscriber])

    respond_to do |format|
      if @launchsubscriber.save
        format.html { redirect_to :home, notice: 'Thanks!  We\'ll be in touch.' }
        format.json { render json: @launchsubscriber, status: :created, location: @launchsubscriber }
      else
        format.html { render action: "new" }
        format.json { render json: @launchsubscriber.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /launchsubscribers/1
  # PUT /launchsubscribers/1.json
  def update
    @launchsubscriber = Launchsubscriber.find(params[:id])

    respond_to do |format|
      if @launchsubscriber.update_attributes(params[:launchsubscriber])
        format.html { redirect_to @launchsubscriber, notice: 'Launchsubscriber was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @launchsubscriber.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /launchsubscribers/1
  # DELETE /launchsubscribers/1.json
  def destroy
    @launchsubscriber = Launchsubscriber.find(params[:id])
    @launchsubscriber.destroy

    respond_to do |format|
      format.html { redirect_to launchsubscribers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/launchsubscribers_helper.rb
module LaunchsubscribersHelper
end

app/views/launchsubscribers/_form.html.erb
<%= form_for(@launchsubscriber) do |f| %>
  <% if @launchsubscriber.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@launchsubscriber.errors.count, "error") %> prohibited this launchsubscriber from being saved:</h2>

      <ul>
      <% @launchsubscriber.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= f.text_field :email %>
    <%= f.submit " "%>
  </div>

<% end %>

app/views/launchsubscribers/edit.html.erb
<h1>Editing launchsubscriber</h1>

<%= render 'form' %>

<%= link_to 'Show', @launchsubscriber %> |
<%= link_to 'Back', launchsubscribers_path %>

app/views/launchsubscribers/index.html.erb
<h1>Listing launchsubscribers</h1>

<table>
  <tr>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @launchsubscribers.each do |launchsubscriber| %>
  <tr>
    <td><%= launchsubscriber.email %></td>
    <td><%= link_to 'Show', launchsubscriber %></td>
    <td><%= link_to 'Edit', edit_launchsubscriber_path(launchsubscriber) %></td>
    <td><%= link_to 'Destroy', launchsubscriber, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Launchsubscriber', new_launchsubscriber_path %>

app/views/launchsubscribers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Email:</b>
  <%= @launchsubscriber.email %>
</p>


<%= link_to 'Edit', edit_launchsubscriber_path(@launchsubscriber) %> |
<%= link_to 'Back', launchsubscribers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rentalutions</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>